[package]
name = "curl-p"
version = "0.2.0"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Curl-p implementation in Rust"

[lib]
name = "curl"

[dependencies]
sponge-preview = "0.2.0"