[package]
name = "curl-p"
version = "0.3.0"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Curl-p implementation in Rust"

[lib]
name = "curl"

[dev-dependencies]
criterion = "0.2"
rand = "0.6"

[[bench]]
name = "random_hash"
harness = false